apiVersion: v1
kind: Pod
metadata:
  name: bulba-baby-pod
  namespace: signal-town
  labels:
    app: bulba-baby
    posemon: bulba-baby
spec:
  containers:
    - name: bulba-baby
      image: nginx
      ports:
        - containerPort: 80
