[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yellow-olive"
version = "0.3.0"
description = "A terminal-native retro Kubernetes adventure inspired by Pokemon Yellow."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Anubhav Sanyal" }
]
keywords = ["kubernetes", "textual", "terminal-game", "retro", "learning","tui"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Education",
  "Topic :: Games/Entertainment",
  "Topic :: Software Development",
]
dependencies = [
  "ascii_magic==2.7.4",
  "Pillow==12.1.1",
  "pygame==2.6.1",
  "rich==14.3.3",
  "textual==8.0.2",
]

[project.urls]
Homepage = "https://github.com/Anubhav9/Yellow-Olive"
Repository = "https://github.com/Anubhav9/Yellow-Olive"
Issues = "https://github.com/Anubhav9/Yellow-Olive/issues"

[project.scripts]
yellow-olive = "app:cli"

[tool.setuptools]
include-package-data = true
py-modules = ["app", "global_constants"]

[tool.setuptools.packages.find]
where = ["."]
include = [
  "challenge_files*",
  "media*",
  "scenarios*",
  "screens*",
  "services*",
  "utils*",
]
namespaces = true

[tool.setuptools.package-data]
challenge_files = ["*.yaml"]
media = ["resources/**/*"]
scenarios = ["**/*.yaml", "**/*.yml"]

[tool.setuptools.data-files]
"." = ["app.tcss"]
scripts = ["scripts/*.sh"]
