ACADEMY_SCREEN_DIALOGUE = """=============== YELLOW OLIVE ACADEMY ===============
LEARN KUBERNETES PODS IN YOUR BROWSER.

THE ACADEMY OPENS IN A NEW TAB WITH PIXEL-ART
LESSONS, A CLASSROOM, AND PROFESSOR QUACK.

CHAPTER 1 - PODS:
[1.1] What is a Pod?
[1.2] Containers in a Pod
[1.3] One IP address
[1.4] Shared storage
[1.5] Pod phases
[1.6] Labels
[1.7] Restart policy

CONTROLS:
CLICK BUTTONS TO NAVIGATE.
USE NEXT TO MOVE THROUGH LESSONS.

IF THE BROWSER DID NOT OPEN, VISIT THE LINK BELOW.
"""
