ACADEMY_SCREEN_DIALOGUE = """=============== YELLOW OLIVE ACADEMY ===============
THE RETRO TUI ACADEMY FOR LEARNING KUBERNETES.

BEFORE YOU FIX A CLUSTER, IT HELPS TO SEE ONE.
THE ACADEMY OPENS IN YOUR BROWSER AND DRAWS THE MAP
ONE PIECE AT A TIME, IN GLORIOUS PIXEL ART.

LESSON 01 - INTRO TO KUBERNETES AND PODS:
[01] NODE        => THE MACHINE EVERYTHING LANDS ON
[02] NAMESPACE   => A VIRTUAL CLUSTER INSIDE THE CLUSTER
[03] POD         => THE SMALLEST THING YOU DEPLOY
[04] CONTAINER   => THE IMAGE AND PROCESS INSIDE THE POD
[05] SIDECARS    => WHEN ONE POD HOLDS MANY CONTAINERS

MORE LESSONS WILL LAND HERE AS THE ACADEMY GROWS.

CONTROLS:
PRESS SPACE (OR TAP) TO ADVANCE EACH LESSON.

IF THE BROWSER DID NOT OPEN, VISIT THE LINK BELOW.
"""
