HELP_SCREEN_DIALOGUE = """=============== POCKET HELP CARTRIDGE ===============
WELCOME, TRAINER. THIS FIELD GUIDE WILL HELP YOU NAVIGATE
THE WORLD OF PROJECT YELLOW OLIVE.

[01] WHAT IS YELLOW OLIVE?
A RETRO-STYLE KUBERNETES ADVENTURE WHERE EVERY CHALLENGE
IS A REAL CLUSTER PROBLEM IN DISGUISE.
YOU PLAY THE STORY, TRACE THE BUG, AND RESTORE ORDER.

WORLD DEX:
POSEMON  => CONTAINER
POKEPOD  => POD
TOWN     => NAMESPACE

[02] TRAINER COMMANDS
`psyquack validate`  => ASK PSYQUACK TO CHECK YOUR FIX
`psyquack back`      => RETURN TO THE PREVIOUS SCREEN

[03] TERMINAL FIELD NOTE
THIS GAME WINDOW HANDLES STORY, DIALOGUE, AND INPUT.
YOUR SECOND TERMINAL IS THE COMMAND CHAMBER.
THAT IS WHERE YOU WILL USE `kubectl`.

[04] MEOW COINS
MEOW COINS MARK YOUR PROGRESS AS A TRAINER.
COMPLETE BATTLES, SOLVE MISSIONS, AND GROW YOUR SCORE.

[05] CHARACTER LOG
PROFESSOR BALD UNCLE:
YOUR GUIDE THROUGH THE LAB. WISE, ECCENTRIC, AND PRECISE.

ELECTROMON:
YOUR PARTNER IN THE FIELD. IF ELECTROMON IS IN TROUBLE,
THE CLUSTER IS USUALLY ASKING FOR HELP.

PSYQUACK:
THE LAB'S SHARP-EYED VALIDATOR. IT DOES NOT GUESS.
IT ONLY APPROVES SOLUTIONS THAT TRULY WORK.

STAY SHARP, TRAINER. THE CLUSTER WILL NOT HEAL ITSELF.
======================================================
"""
