apiVersion: v1
kind: Service
metadata:
  name: bulba-baby-service
  namespace: signal-town
spec:
  type: ClusterIP
  selector:
    app: bulba-baby
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
