apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-reader
  namespace: gold-rush-city
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["city-vault-gold"]
    verbs: ["get"]
