apiVersion: v1
kind: Pod
metadata:
  name: electromon-pod
  labels:
    type: pod
  namespace: oakwood-meadows
spec:
  restartPolicy: OnFailure
  containers:
    - name: elctromon-container
      image: nginx
