HELP_SCREEN_DIALOGUE = """=============== POCKET HELP CARTRIDGE ===============
HEY TRAINER! READY TO PATCH THE CLUSTER?

[01] WHAT IS YELLOW OLIVE?
RETRO ADVENTURE. REAL KUBERNETES PROBLEMS.
YOU PLAY. YOU DEBUG. YOU LEARN.

WORLD DEX:
POSEMON  => CONTAINER
POKEPOD  => POD
TOWN     => NAMESPACE

[02] LIVE COMMANDS
`psyquack validate`  => CHECK YOUR FIX
`psyquack back`      => GO BACK TO PREVIOUS SCREEN

[03] TERMINAL TIP
GAME WINDOW = STORY + INPUT
SECOND TERMINAL = COMMAND CHAMBER
USE `kubectl` IN THE COMMAND CHAMBER.

[04] MEOW COINS
MEOW COINS = TRAINER SCORE.
CLEAR BATTLES. EARN COINS.
MORE MISSIONS, MORE COINS.

[05] CHARACTER LOG
PROFESSOR BALD UNCLE:
YOUR MENTOR. OLD SCHOOL. ALWAYS PRECISE.

ELECTROMON:
YOUR PARTNER. IF HE IS STUCK, SOMETHING IS OFF.

PSYQUACK:
THE VALIDATOR. NO GUESSWORK. ONLY CORRECT FIXES.

TRAIN HARD. TYPE FAST. STABILIZE THE CLUSTER.
======================================================
"""
